version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: article_backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/article_app_development
    command: ["bin/rails", "server", "-b", "0.0.0.0"]
    volumes:
      - ./app_data:/app/data

  db:
    image: postgres:12
    container_name: article_app_development
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: article_app_development
    volumes:
      - ./db_data:/var/lib/postgresql/data
  