default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: postgres
  password: postgres

development:
  <<: *default
  database: article_app_development

test:
  <<: *default
  database: article_app_test

production:
  <<: *default
  database: article_app_production
  username: article_app
  password: <%= ENV["ARTICLE_APP_DATABASE_PASSWORD"] %>
